# Generated by Django 5.1.5 on 2025-02-10 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('experiences', '0003_perk_category_alter_perk_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perk',
            name='category',
        ),
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
